function wrapper_WaveletDespike(Inii,Opref,varargin)

% Default options from WaveletDespike, provided as strings to match how
% they will come when MCR command line is used
DefaultOpts = struct( ...
    'wavelet','d4', ...
    'threshold','10', ...
    'boundary','reflection', ...
    'chsearch','moderate', ...
    'nscale','liberal', ...
    'compress','1', ...
    'SP','1', ...
    'LimitRAM','0', ...
    'verbose','1' ...
    );

% Update with provided command line options
Opts = parseInOpts(DefaultOpts,varargin);

% Convert numeric opts from string so they are acceptable to WaveletDespike
for opt = {'threshold','compress','SP','LimitRAM','verbose'}
    Opts.(opt) = str2double(Opts.(opt));
end

% Finally, run WaveletDespike with converted options
WaveletDespike( ...
    Inii, ...
    Opref, ...
    'wavelet',Opts.wavelet, ...
    'threshold',Opts.threshold, ...
    'boundary',Opts.boundary, ...
    'chsearch',Opts.chsearch, ...
    'nscale',Opts.nscale, ...
    'compress',Opts.compress, ...
    'SP',Opts.SP, ...
    'LimitRAM',Opts.LimitRAM, ...
    'verbose',Opts.verbose ...
    );
